### ISSUE TITLE
Not able to start Blox locally

### ISSUE THREAD

**Issue by arun-gupta** [blox/blox#189]
Configured Blox locally as explained at:

https://github.com/blox/blox/tree/dev/deploy#deploy-blox-locally-to-docker

http://localhost:2000 is giving a 404.

**Comment by kylbarnes** [comment]
@arun-gupta This is because we don't have anything configured at the `/` route. All URIs are prefixed with `/v1`. An example URL would be:

http://localhost:2000/v1/environments

You can find our swagger definition with all URIs [here](https://github.com/blox/blox/blob/dev/daemon-scheduler/swagger/v1/swagger.json). Let me know if you have any other questions.

**Comment by arun-gupta** [comment]
@kylbarnes The docs talk about checking out localhost:2000 and that's where the confusion came from.

**Comment by kylbarnes** [comment]
Thanks for the response. I'm going to close this issue. Please let me know if you need anything further regarding this.
