### ISSUE TITLE
Questions/clarifications around daemon scheduler design doc 

### ISSUE THREAD

**Issue by aaithal** [blox/blox#208]
Hi,

I was reading https://github.com/blox/blox/blob/dev/docs/daemon_design.md and had a few questions/comments:
1. In the [Starting a Deployment](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#starting-a-deployment) section, `Attributes` filed is listed as `list of string (optional)`. Can we expand it to include key-value style attributes supported by ECS as well?
2. What's the recommendation between the two alternatives (event stream and snapshots) in [State Service](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#state-service-1)?
3. Will there be a maximum cluster size beyond which daemon scheduler will not deploy tasks (related to https://github.com/blox/blox/blob/dev/docs/daemon_design.md#manager-creation)? 
4. Is idempotent task launch support from ECS a must-have for [Scheduling Manager](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#scheduling-manager-1)? 
5. Should there be an `Availability Considerations` in this document as well? As in, how are failure scenarios being handled when any of the dependent services (especially DynamoDB) exhibit availability issues?

Thanks,
Anirudh

**Comment by narehayrapetyan** [comment]
@aaithal thanks for the feedback.

1. Good idea.

2. We need a little more investigation on state service but I will make that more clear in the doc.

3. Do you mean cluster size tasks will be deployed to or cluster where manager tasks live?

4. What I mean by idempotent tasks is when tasks are launched on instances to be true daemon tasks there can only be one on the instance, so the instanceID - taskID pair should be unique. There is no way to guarantee that the same task won't be started twice on the same instance because of call failures, eventual consistency, etc. So while it shouldn't be a problem most of the time and we can improve our chances of not starting the same task on the instance by listing tasks before starting them, we cannot guarantee that there will only ever be one daemon task on the instance.

5. That's a good point. There is an availability and recovery section in the infrastructure doc I should have a PR out for soon but I will add more details about other dependencies here.

**Comment by narehayrapetyan** [comment]
@aaithal please reopen if this doesn't answer your questions. Also see the updated design doc.
