### ISSUE TITLE
Force push to "dev" branch (aka resetting git commit history)

### ISSUE THREAD

**Issue by aaithal** [blox/blox#216]
Why was this done? I understand wanting to get rid of the code that corresponds to the self-managed version of blox to an extent. But, why delete all commits, effectively resetting the history of the repo? It doesn't seem to customer friendly to lose references to past contributors to the repo and the code that still has open issues related to it. At the very least, can we rebase `dev` from `master` and replay the new commits on top of a different one where the old code is deleted?

**Comment by jahkeup** [comment]
The `dev` branch appears to have been created as an orphan before what looks to be force pushing (likely a delete + push). It would make more sense to have a commit that _deletes_ the files in the previous code base - if that's direction it's moving - and then rebase on that. Losing the history is unfortunate for developers and confusing for all.

**Comment by wjbuys** [comment]
Apologies if this was unexpected. My reasoning behind this was explained in a [PR comment](https://github.com/blox/blox/pull/213#issuecomment-319515469) (which is probably not visible enough):
> Edit: Just to explain the force push here, we were faced with two options:
> - continue this as a continuous line of history from the current `dev` branch. This would introduce a commit with a huge diff of "delete everything", and would force us to carry around the history of the unrelated GoLang codebase in every (non-shallow) clone. Users pulling the dev branch would immediately get conflicts for all their changes (since we deleted all files).
> - create this as a new orphan branch and start from scratch, then force push into `dev` to switch over the history. New clones get the actually-in-development code, with none of the unrelated baggage. The old code is still available in the `v0.3` branch. If anyone has cloned the repo at the `dev` branch and tries to pull, they'll get slightly more cryptic conflicts for all changes.
>
> Neither of these are great options; we opted to go for keeping the history separate, and dealing with the fallout of users' clones of the dev branch no longer being pullable. The solution in either case is for users to switch to the `v0.3` branch in their working copy, and pull from that.

For any contributors that have forks or working copies based off of the `dev` branch, and who wish to continue working on the 0.3 codebase, the fix is the same: switch the upstream branch to `v0.3`:

```
git fetch --all
git checkout dev
git branch --set-upstream-to origin/v0.3
```

Since the two codebases are entirely unrelated, my thinking was that the history is not useful on the same branch as the new code. Usually, we would just create a new repository, but we wanted to keep primary development in the main `blox/blox` repo. And so, here we are.

If it turns out that this change is too confusing, or has other unforseen negative effects, we can figure out how to back out the change and use the continuous-line-of-history approach instead.

**Comment by wjbuys** [comment]
> It doesn't seem to customer friendly to lose references to past contributors to the repo and the code that still has open issues related to it.

> Losing the history is unfortunate for developers and confusing for all.

Losing history would indeed be unfortunate; however, it's worth noting that the history (in both cases) will be maintained, just on a different branch ([`v0.3`](https://github.com/blox/blox/tree/v0.3)), which is where any future development on v0.3 would be happening.

**Comment by aaithal** [comment]
> For any contributors that have forks or working copies based off of the `dev` branch, and who wish to continue working on the 0.3 codebase, the fix is the same: switch the upstream branch to `v0.3`

In that case, why rewrite the history? Why not pick the option that's least confusing to customers (of deleting code with a commit and update the README to point customers to the branch where we are stashing old code)? Wouldn't that be less confusing?

**Comment by wjbuys** [comment]
The update to the `README` is a good idea regardless of path, I think.

The core of the problem here is that we're trying to shoehorn unrelated code into the same `dev` branch. This is going to cause existing contributors pain no matter what we do.

After thinking on this a bit more, there's a third option here that we considered briefly which I think is more tractable now that we're seeing the fallout from the hard changeover: keep the `dev` branch as the line of history for `v0.3`, and make a new default branch with the separate history for the new project:

```
HEAD, development* : 0dbdda1c8ee4da28b3ae7f8e260e9c5f569f4374
dev, v0.3: 8f24ef6f6229bae7baf09ccb76f3cbdc847e50f1

* (or dev-managed, or another good name)
```
That way, existing forks still work, there's no point where someone would pull either a history change or a commit that introduces conflicts. However, new clones will pick up the new default branch, and work from the new line of history, and visitors to `github.com/blox/blox` will see the new default branch instead of `dev`.

The only cost is potential confusion around the naming of the legacy `dev` branch. It seems like this is a reasonable tradeoff that gets us the best of both worlds. Thoughts? Would this be as (or more) acceptable as rebasing the new history onto the old `dev` branch?

**Comment by wjbuys** [comment]
Okay, @narehayrapetyan, @aaithal and I had some offline discussion, and to try and minimize confusion, we're going to got with resetting everything back to the way it was, and preserving the history of the `dev` branch.

Steps:
- [x] make a temporary `managed` branch off of [the current tip of dev](https://github.com/blox/blox/commit/0dbdda1c8ee4da28b3ae7f8e260e9c5f569f4374)
- [x] unprotect the `dev` branch
- [x] reset `dev` back to [the commit](https://github.com/blox/blox/commit/0f3999bed385a4cb53d1192b932638bda05a420d) it was at before the switchover to the new code, and `git push origin dev --force-with-lease`. This should leave the repo in the same state as it was before we started
- [x] re-protect the `dev` branch
- [x] submit a PR against `dev` that deletes all the current code. For clear communication purposes:
    - this should add a section in the README about where to find the `v0.3` branch
    - the PR text itself should explain what we're doing and why
    - since it's this commit that will conflict with any attempts to merge existing upstream code and therefore show up in git output, the actual commit message should include a brief summary of what happened and why, and link to the PR
- [x] rebase the `managed` branch off of this new tip of `dev`.
- [x] delete the `managed` branch

**Comment by wjbuys** [comment]
About to force push `dev` back into `blox/blox:dev`:
```
$ git branch- v | grep dev
* dev                  0f3999b Clarifying $GOPATH (#209)
```

**Comment by wjbuys** [comment]
Force pushed:
```
$ git push origin --force-with-lease dev:dev
Total 0 (delta 0), reused 0 (delta 0)
To github.com:blox/blox.git
 + 0dbdda1...0f3999b dev -> dev (forced update)
```

**Comment by wjbuys** [comment]
#214 is re-opened, just needs a few doc changes before merging.

**Comment by wjbuys** [comment]
Okay, the dev branch is now the new codebase with the old history intact. Resolving.
